import { User, Post, Comment } from '@/core/types';

export const defaultUsers: User[] = [
  {
    id: '1',
    username: 'adm',
    email: 'adm@adm.com',
    password: '123456',
    avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    cover: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
    bio: 'Administrador do sistema',
    createdAt: new Date(),
    updatedAt: new Date(),
    friends: ['2', '3'],
  },
  {
    id: '2',
    username: 'maria',
    email: 'maria@email.com',
    password: '123456',
    avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    cover: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
    bio: 'Maria, fotógrafa e viajante',
    createdAt: new Date(),
    updatedAt: new Date(),
    friends: ['1', '3'],
  },
  {
    id: '3',
    username: 'joao',
    email: 'joao@email.com',
    password: '123456',
    avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    cover: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429',
    bio: 'João, amante de esportes',
    createdAt: new Date(),
    updatedAt: new Date(),
    friends: ['1', '2'],
  },
];

export const defaultPosts: Post[] = [
  {
    id: '101',
    userId: '2',
    imageUrl: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308',
    caption: 'Amanhecer incrível na montanha!',
    likes: 2,
    likedBy: [],
    comments: [
      {
        id: 'c1',
        postId: '101',
        userId: '1',
        content: 'Lindo lugar!',
        createdAt: new Date(),
        updatedAt: new Date(),
        likedBy: [],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '102',
    userId: '3',
    imageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9',
    caption: 'Corrida matinal no parque',
    likes: 1,
    likedBy: [],
    comments: [
      {
        id: 'c2',
        postId: '102',
        userId: '2',
        content: 'Parabéns pelo ritmo!',
        createdAt: new Date(),
        updatedAt: new Date(),
        likedBy: [],
      },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '103',
    userId: '1',
    imageUrl: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b41',
    caption: 'Bem-vindo ao sistema! #admin',
    likes: 0,
    likedBy: [],
    comments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
